---
title: "UrbanShift Biodiversity Indicators Pipeline"
author: "Saif Shabou"
date: "`r format (Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
    theme: spacelab
    highlight: tango
    number_sections: yes
    code_folding: hide
---

```{r Libraries, warning=FALSE, message=FALSE, echo = FALSE,  eval = TRUE}

# library(shiny)
library(plotly)
library(leaflet)
library(plyr)
library(dplyr)
library(ggplot2)
library(rgdal)
library(tidyverse)
library(sf)
library(rgeos)
library(httr)
library(jsonlite)
library(raster)
library(data.table)
library(leaflet.providers)
library(knitr)
library(kableExtra)
library(reactable)
library(readxl)
library(vroom)

```

# Pipline overview



# Indicator 1

```{r city-boundary, warning=FALSE, message=FALSE, echo = TRUE,  eval = TRUE}

# read all boundaries
urbanshift_boundaries = st_read("https://cities-urbanshift.s3.eu-west-3.amazonaws.com/data/boundaries/administrative_boundaries.geojson",
                                quiet = TRUE)

# change San jose boundary status
urbanshift_boundaries[urbanshift_boundaries$city_name == "CRI-San_Jose" & urbanshift_boundaries$boundary_data_source == "cities360", "boundary_use"] = TRUE
urbanshift_boundaries[urbanshift_boundaries$city_name == "CRI-San_Jose" & urbanshift_boundaries$boundary_data_source == "city_specific", "boundary_use"] = FALSE

# change IDN-Jakarta boundary status
urbanshift_boundaries[urbanshift_boundaries$city_name == "IDN-Jakarta" & urbanshift_boundaries$boundary_data_source == "cities360", "boundary_use"] = TRUE
urbanshift_boundaries[urbanshift_boundaries$city_name == "IDN-Jakarta" & urbanshift_boundaries$boundary_data_source == "city_specific", "boundary_use"] = FALSE

# filter right boundaries
urbanshift_boundaries = urbanshift_boundaries[urbanshift_boundaries$boundary_use == TRUE, ]

# cities list
urbanshift_cities = urbanshift_boundaries$city_name

# extract cities with wrong boundaries
# urbanshift_cities = urbanshift_cities[! urbanshift_cities %in% c("ARG-Mar_del_Plata",
#                                                                  "IDN-Balikpapan",
#                                                                  "CHN-Ningbo")]

```

## Compute world cover statistics by city

```{r city-world-cover-stat, warning=FALSE, message=FALSE, echo = TRUE,  eval = FALSE}

# compute statistics on world cover distribution at the city level

world.cover.city.stat = function(city_worldcover, year,city_id){
  city_worldcover_stat = as.data.frame(city_worldcover_raster) %>%
    rename_at(1, ~"class" ) %>% 
    drop_na(class) %>% 
    group_by(class) %>%
    tally() %>%
    mutate(area = n * res(city_worldcover_raster)[1] * res(city_worldcover_raster)[2]) %>% 
    dplyr::select(land_cover_classes = class,
                  nb_cells = n) %>% 
    mutate(land_cover_percent = round(nb_cells/sum(nb_cells) * 100,2))%>% 
    add_column(year = year,
               city_id = city_id) %>% 
    arrange(desc(land_cover_percent)) %>%
    mutate_at("land_cover_classes", as.character) %>%
    mutate(land_cover_classes = recode(land_cover_classes,
                                       "10" =  "Trees",
                                       "20" = "Shrubland" ,
                                       "30" = "Grassland",
                                       "40" = "Cropland",
                                       "50" =  "Built-up",
                                       "60" = "Barren / sparse vegetation",
                                       "70" = "Snow and ice",
                                       "80" = "Open water",
                                       "90" = "Herbaceous wetland",
                                       "95" = "Mangroves",
                                       "100" = "Moss and lichen")) %>% 
    dplyr::select(city_id = city_id,
                  year = year,
                  land_cover_class = land_cover_classes,
                  land_percent = land_cover_percent)
  
  return(city_worldcover_stat)
}


# initialize empty dataframe for storing indicators
cities_worldcover_stat = data.frame(city_id = as.character(),
                                    land_cover_class = as.character(),
                                    land_percent = as.numeric(),
                                    year = as.numeric())

for(i in 1:length(urbanshift_cities)){
  
  # print(i)
  
  city_id = urbanshift_cities[i]
  print(city_id)
  
  # extract city boundary
  city_boundary = urbanshift_boundaries[urbanshift_boundaries$city_name == city_id, ]
  
  # read world cover by city
  
  worldcoverc_data_path = paste("https://cities-urbanshift.s3.eu-west-3.amazonaws.com/data/land_use/esa_world_cover/world_cover_",
                                city_id,
                                ".tif",
                                sep = "")
  city_worldcover_raster = raster(worldcoverc_data_path)
  city_worldcover  = raster::mask(city_worldcover_raster,
                                  city_boundary)
  
  city_worldcover_stat = city_worldcover_stat = world.cover.city.stat(city_worldcover = city_worldcover,
                                                                      year = 2020,
                                                                      city_id = city_id)
  
  
  cities_worldcover_stat = rbind(cities_worldcover_stat,
                                 city_worldcover_stat)
}

# plot table
cities_worldcover_stat %>% 
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F, font_size = 13)%>% 
  scroll_box(width = "100%", height = "500px")

# store outputs
write.csv(cities_worldcover_stat,
          "./data/cities_worldcover_stat.csv",
          row.names = FALSE)
```

## Compute percent of natural area

```{r compute-i1, warning=FALSE, message=FALSE, echo = TRUE,  eval = FALSE}

cities_worldcover_stat = read.csv("./data/cities_worldcover_stat.csv")

# initialize empty dataframe for storing indicators
biodiversity_indicators = data.frame(city_id = as.character(),
                                     year =  as.numeric(),
                                     indicator_name = as.character(),
                                     indicator_number = as.character(),
                                     value = as.numeric(),
                                     score = as.numeric())



# function to compute I1
compute.i1 = function(city_id,city_worldcover_stat,year){
  
  natural_areas_classes = c('Trees','Shrubland','Grassland','Snow/ice','Open water','Herbaceous wetland',
                            'Mangroves','Moss/lichen')
  
  biodiversity_indicators = city_worldcover_stat %>% 
    mutate(natural_areas_class =
             case_when(land_cover_class %in% natural_areas_classes ~ "Natural areas", 
                       !land_cover_class %in% natural_areas_classes ~ "Non Natural areas")
    ) %>% 
    group_by(natural_areas_class) %>% 
    summarise(natural_areas_percent = sum(land_percent)) %>% 
    filter(natural_areas_class == "Natural areas") %>% 
    add_column(city_id = city_id,
               year = year,
               indicator_name = "Proportion of natural areas",
               indicator_number = "I1") %>% 
    rename(value = natural_areas_percent) %>% 
    mutate(score =
             case_when(value <  1 ~ "0", 
                       value <=  6.9 ~ "1", 
                       value <=  13.9 ~ "2",
                       value <=  20 ~ "3",
                       value >  20 ~ "4")) %>% 
    dplyr::select(city_id,
                  year,
                  indicator_name,
                  indicator_number,
                  value,
                  score)
  
  return(biodiversity_indicators)
}


# compute I1 for urbanshift cities

for(i in 1:length(urbanshift_cities)){
  
  # print(i)
  
  city_id = urbanshift_cities[i]
  # print(city_id)
  
  city_worldcover_stat = cities_worldcover_stat[cities_worldcover_stat$city_id == city_id, ]
  
  biodiversity_inidcators_I1 = compute.i1(city_id = city_id,
                                          city_worldcover_stat = city_worldcover_stat,
                                          year = 2020)
  
  biodiversity_indicators = rbind(biodiversity_indicators,
                                  biodiversity_inidcators_I1)
  
}

# store outputs
write.csv(biodiversity_indicators,
          "./data/biodiversity_indicators.csv",
          row.names = FALSE)


```

```{r plot-i1, warning=FALSE, message=FALSE, echo = TRUE,  eval = TRUE}

biodiversity_indicators = read.csv("./data/biodiversity_indicators.csv")

# plot table
biodiversity_indicators %>% 
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F, font_size = 13)%>% 
  scroll_box(width = "100%", height = "500px")
```

# Indicator 2

# Indicator 3

## Extract Species occurence data by city

```{r extract-gbif-city, warning=FALSE, message=FALSE, echo = TRUE,  eval = FALSE}
#########################
# get country gbif data

gbif_data = vroom('./data/biodiversity/data/gbif/gbif_db.zip')

#########################
# read all boundaries
urbanshift_boundaries = st_read("https://cities-urbanshift.s3.eu-west-3.amazonaws.com/data/boundaries/administrative_boundaries.geojson",
                                quiet = TRUE)

# change San jose boundary status
urbanshift_boundaries[urbanshift_boundaries$city_name == "CRI-San_Jose" & urbanshift_boundaries$boundary_data_source == "cities360", "boundary_use"] = TRUE
urbanshift_boundaries[urbanshift_boundaries$city_name == "CRI-San_Jose" & urbanshift_boundaries$boundary_data_source == "city_specific", "boundary_use"] = FALSE

# change IDN-Jakarta boundary status
urbanshift_boundaries[urbanshift_boundaries$city_name == "IDN-Jakarta" & urbanshift_boundaries$boundary_data_source == "cities360", "boundary_use"] = TRUE
urbanshift_boundaries[urbanshift_boundaries$city_name == "IDN-Jakarta" & urbanshift_boundaries$boundary_data_source == "city_specific", "boundary_use"] = FALSE

# filter right boundaries
urbanshift_boundaries = urbanshift_boundaries[urbanshift_boundaries$boundary_use == TRUE, ]

# add country iso code 2
urbanshift_boundaries = urbanshift_boundaries %>% 
  mutate(country_iso2 = str_sub(country_iso3, 1,2))

urbanshift_boundaries[urbanshift_boundaries$country_iso2 == "CH", "country_iso2"] = "CN"

#########################

for(i in 1:nrow(urbanshift_boundaries)){
  
  print(i)
  # get city name
  city_name = urbanshift_boundaries$city_name[i]
  print(city_name)
  
  # get city boundary
  city_boundary =  urbanshift_boundaries[urbanshift_boundaries$city_name == city_name, ]
  
  # get country iso code
  country_iso2 = city_boundary$country_iso2
  
  # filter country GBOF data
  gbif_data_country = gbif_data %>% 
    filter(countryCode == country_iso2) %>% 
    dplyr::select(class,order,family,genus,
                  countryCode,stateProvince,
                  decimalLatitude,decimalLongitude,
                  eventDate,year)
  
  # convert country gbif data to sf objects
  gbif_data_country_sf = st_as_sf(gbif_data_country, 
                                  coords = c("decimalLongitude", "decimalLatitude"),
                                  crs = st_crs(4326))
  
  # filter gbif within city boundary
  gbif_city_sf = st_join(gbif_data_country_sf, city_boundary, join = st_intersects)
  
  # drop points outside of boundaries
  gbif_city_sf = gbif_city_sf %>% 
    drop_na(id)
  
  # transform into data frame with lat,long coorindates
  gbif_city_df = gbif_city_sf %>% 
    mutate(lat = unlist(map(gbif_city_sf$geometry,1)),
           long = unlist(map(gbif_city_sf$geometry,2))) 
  
  nrow(gbif_city_df)
  
  #########################
  # plot 
  
  plot(st_geometry(city_boundary))
  plot(gbif_city_df$geometry,
       add = TRUE,
       col = "red")
  
  
  #########################
  # store output
  file_name = paste("GBIF",city_name, sep = "-")
  
  write.csv(gbif_city_df,
            paste("./data/biodiversity/data/gbif/",file_name,".csv", sep = ""),
            row.names = FALSE)
  
}
```


```{r extract-gbif-city-plot, warning=FALSE, message=FALSE, echo = TRUE,  eval = TRUE}

city_name = "CRI-San_Jose"
city_gbif = read.csv(paste("./data/biodiversity/gbif/GBIF-",city_name,".csv", sep = ""))
city_boundary = urbanshift_boundaries[urbanshift_boundaries$city_name == city_name, ]

# filter AVES
city_gbif_Aves = city_gbif %>% 
  filter(class == "Aves")

# plot map
leaflet(data = city_boundary, height = 500, width = "100%") %>% 
  addTiles() %>%
  addProviderTiles("OpenStreetMap.France", group = "OSM") %>%
  addProviderTiles(providers$CartoDB.DarkMatter , group = "CartoDB") %>% 
  # Add boundaries
  addPolygons(data = city_boundary,
              group = "Administrative boundaries",
              stroke = TRUE, color = "black", weight = 3,dashArray = "3",
              smoothFactor = 0.3, fill = TRUE, fillOpacity = 0.2,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.3,
                bringToFront = FALSE)) %>%
  # add cluster markers
  addMarkers(city_gbif_Aves$lat,
             city_gbif_Aves$long, 
             popup = ~as.character(city_gbif_Aves$family),
             # label = label_birds2020,
             clusterOptions = markerClusterOptions(),
             group = "Birds clusters") %>%
  # add birds layer
  addCircleMarkers(city_gbif_Aves$lat,
                   city_gbif_Aves$long, 
                   radius = 3,
                   fillColor = "green",
                   color  = "black",
                   stroke = TRUE,
                   weight = 0.8,
                   fillOpacity = 0.6,
                   popup = ~as.character(city_gbif_Aves$family),
                   # label = label_birds2020,
                   group = "Birds observations") %>% 
  # Layers control
  addLayersControl(
    baseGroups = c("OSM","CartoDB"),
    overlayGroups = c("Birds observations","Birds clusters"),
    options = layersControlOptions(collapsed = FALSE)
  ) 


```